name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Clear npm cache
        run: npm cache clean --force


      - name: Install dependencies
        working-directory: frontend_app
        run: npm install --legacy-peer-deps

      - name: Debug env
        run: |
              echo "VITE_BASE_URL=$VITE_BASE_URL"
              echo "VITE_API_URL=$VITE_API_URL"
        env:
              VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
              VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Build Vite app
        working-directory: frontend_app
        run: npm run build
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_AUTH_METHOD: entra
          VITE_AZURE_CLIENT_ID: ${{ secrets.VITE_AZURE_CLIENT_ID }}
          VITE_AZURE_TENANT_ID: ${{ secrets.VITE_AZURE_TENANT_ID }}
          VITE_AZURE_BACKEND_SCOPE: ${{ secrets.VITE_AZURE_BACKEND_SCOPE }}
          VITE_AZURE_AUDIENCE: ${{ secrets.VITE_AZURE_AUDIENCE }}
          VITE_APP_TITLE: Perth and Kinross Council
          VITE_APP_SUBTITLE: Sonic Brief Demo

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend_app"
          output_location: "dist"